version: "3.9"

services:
  web:
    build: .
    command: pipenv run start
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    env_file: .env
  
  redis:
    image: redis:6.2.6-alpine
    