version: "3.7"

services:
  web:
    build: .
    command: pipenv run start
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./.env
    depends_on:
      - db

  db:
    image: postgres:14.1
    restart: always
    ports:
      - 5432:5432
    env_file: .env